// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy1MIkw4nkV8WXqglpxSiTrJzR0K1oifo',
    appId: '1:62862337284:android:1a920679aa6866bbaddc51',
    messagingSenderId: '62862337284',
    projectId: 'microcreditmanager-665cf',
    storageBucket: 'microcreditmanager-665cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRk3WHMN9bUq1CxLVhp0tD3rO0Fqj_fIk',
    appId: '1:62862337284:ios:e719c7f8caf6a804addc51',
    messagingSenderId: '62862337284',
    projectId: 'microcreditmanager-665cf',
    storageBucket: 'microcreditmanager-665cf.appspot.com',
    iosClientId: '62862337284-7b0odldg6ac9qn0nitd40fqmccsuhgbn.apps.googleusercontent.com',
    iosBundleId: 'com.microcreditmanager.microcreditmanagerapp',
  );
}
